# Nome da aplica��o
spring.application.name=api
port: 8081

# Configura��o do Console H2 (Acesse: localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:apidb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username= postgres
spring.datasource.password=123456

# Exibir os comandos SQL no console do IntelliJ
spring.jpa.show-sql=true

## Formato padr�o para serializa��o de datas
#spring.jackson.date-format=dd/MM/yyyy HH:mm:ss
## Define o fuso hor�rio (importante para servidores na nuvem)
#spring.jackson.time-zone=America/Sao_Paulo
## Garante que o Jackson trate LocalDateTime como String formatada
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false